markdown: rdiscount
pygments: true
permalink: /beers/:title
auto: true
rdiscount:
  extensions: [smart]

name: Mouse And Lion Ale Project
sideBarName: Mouse &Lion
url: http://zachholman.com
description: Mouse and Lion ale project site.
twitter: omockler
github_user: omockler
gravatar_url: http://www.gravatar.com/avatar/4974bc97093a7364ace30e7eadc49b6a.png